
PREDICTION_TYPE: 'gender'  # Valid values: 'gender' or 'age'

pre-processing:
    MAX_SEQUENCE_LENGTH: 80
    VALIDATION_SPLIT: 0.1


model:
    names:
        - 'BiLSTM_full'
        - '3xConv_2xBiLSTM'
    optimizer: 'adam'
    loss: 'categorical_crossentropy'
    metrics:
        - 'accuracy'
    nb-epochs: 20
    batch-size: 128
