
PREDICTION_TYPE: 'gender'  # Valid values: 'gender' or 'age'

pre-processing:
    MAX_SEQUENCE_LENGTH: 80
    VALIDATION_SPLIT: 0.1


model:
    optimizer: 'adam'
    loss: 'categorical_crossentropy'
    metrics:
        - 'accuracy'
    nb-epochs: 30
    batch-size: 256
