PREDICTION_TYPE: 'gender'  # Valid values: 'gender' or 'age'

pre-processing:
    MAX_NB_WORDS: 50000
    MAX_SEQUENCE_LENGTH: 25
    VALIDATION_SPLIT: 0.1

    # Embedding type can be:
    # - glove.twitter.27B.200d

    EMBEDDINGS_INDEX: 'glove.twitter.27B.200d'


model:
    names: # names of all models to train
#        - '2x512_256LSTM_128full'
#        - '2x512_256GRU'
    optimizer: 'adam'
    loss: 'categorical_crossentropy'
    metrics:
        - 'accuracy'
    nb-epochs: 20
    batch-size: 128
